n=int(input("So tien ban dau: "))
k=int(input("So thang gui: "))
t=float(input("Lai suat/ thang: "))
m=n*(1+k*t)
print("Voi so tien ban dau",n,",sau",k,"thang gui, lai suat",t,"/thang")
print("Thi so tien nhan duoc cuoi ky la",n*(1+k*t))